import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-schedule',
  templateUrl: './schedule.component.html',
  styleUrls: ['./schedule.component.scss']
})
export class MainScheduleComponent implements OnInit {


  scheduleItems = [
    {
      homeTeam: 'Trinity FC',
      awayTeam: 'Polonia FC O30',
      field: 'CT Sportsplex (T), North Branford',
      time: '10:15AM',
      date: 'Sun April 18',
      result: '1-1',
      completed: true,
    },
    {
      homeTeam: 'International FC',
      awayTeam: 'Polonia FC O30',
      field: 'InSports (T), Trumbull',
      time: '10:15AM',
      date: 'Sun April 25',
      result: '1-2',
      completed: true,
    },
    {
      homeTeam: 'Litchfield County Blues',
      awayTeam: 'Polonia FC O30',
      field: 'New Milford HS, New Milford',
      time: '09:00AM',
      date: 'Sun May 02',
      result: '1-6',
      completed: true,
    },
    {
      homeTeam: 'Milford Tuesday',
      awayTeam: 'Polonia FC O30',
      field: '	Peck Place School (G), Orange',
      time: '89:00AM',
      date: 'Sun May 09',
      result: '1-1',
      completed: true,
    },
    {
    homeTeam: 'Hamden All Stars',
    awayTeam: 'Polonia FC O30',
    field: 'West Woods School (G), Hamden',
    time: '10:15AM',
    date: 'Sun May 16',
    result: '-',
    completed: false,
  },
 {
   homeTeam: 'Polonia FC O30',
   awayTeam: 'Coyotes FC',
   field: 'Falcon Field, New Britain',
   time: '11:00AM',
   date: 'Sun May 23',
   result: '-',
   completed: false,
 },
 {
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Milford Amigos',
  field: 'Falcon Field, New Britain',
  time: '09:00AM',
  date: 'Sun June 06',
  result: '-',
  completed: false,
},
{
  homeTeam: 'QPR',
  awayTeam: 'Polonia FC O30',
  field: 'Quinnipiac Park (G), Cheshire',
  time: '09:00AM',
  date: 'Sun June 20',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Club Independiente',
  field: 'Falcon Field, New Britain',
  time: '11:00AM',
  date: 'Sun June 27',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Trinity FC',
  field: 'Falcon Field, New Britain',
  time: '09:00AM',
  date: 'Sun August 22',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'International FC',
  field: 'Falcon Field, New Britain',
  time: '09:00AM',
  date: 'Sun August 29',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Hamden All Stars',
  field: 'Falcon Field, New Britain',
  time: '11:00AM',
  date: 'Sun September 12',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Coyotes FC',
  awayTeam: 'Polonia FC O30',
  field: 'Falcon Field, Meriden',
  time: '08:00AM',
  date: 'Sun September 19',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Milford Amigos',
  awayTeam: 'Polonia FC O30',
  field: 'Pease Road (G), Woodbridge',
  time: '08:00AM',
  date: 'Sun September 26',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Milford Tuesday',
  field: 'Falcon Field, New Britain',
  time: '09:00AM',
  date: 'Sun October 03',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'QPR',
  field: 'Falcon Field, New Britain',
  time: '11:00AM',
  date: 'Sun October 17',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Club Independiente',
  awayTeam: 'Polonia FC O30',
  field: 'Woodruff Field (T), Milford',
  time: '08:00AM',
  date: 'Sun October 24',
  result: '-',
  completed: false,
},
{
  homeTeam: 'Polonia FC O30',
  awayTeam: 'Litchfield County Blues',
  field: 'Falcon Field, New Britain',
  time: '09:00AM',
  date: 'Sun October 31',
  result: '-',
  completed: false,
},
];
  constructor() { }

  ngOnInit() {
  }

}
